### save user & todos
POST http://localhost:3000/todo
Content-Type: application/json

{
   "name": "juha",
   "todos": "play"
}

### fetch user
POST http://localhost:3000/user
Content-Type: application/json

{
    "search_name": "juha"
}

### fetch user
GET http://localhost:3000/user/juha

### delete user
DELETE http://localhost:3000/user/juha

### delete todo
PUT http://localhost:3000/user
Content-Type: application/json

{
    "search_name": "juha",
    "todo": "code"
}