### save user & todos
POST http://localhost:3000/todo
Content-Type: application/json

{
   "name": "juha",
   "todos": "code"
}

### fetch user
POST http://localhost:3000/user/juha
Content-Type: application/json

{
    "search_name": "juha"
}

### fetch user
GET http://localhost:3000/user/juha
